### ISSUE TITLE
Déplacer redirection hook vers une dédiée dans la page

### ISSUE THREAD

**Issue by MachiganMC** [mux99/pocket-bot#24]
La redirection via le fichier `server.hook.js` dans la fonction `hook` redirige trop souvent vers la page de login ou la page d'accueil, même si elle devrait nous laisser aller sur la page désirée.

**Comment by noelibon** [comment]
> La redirection via le fichier `server.hook.js` dans la fonction `hook` redirige trop souvent vers la page de login ou la page d'accueil, même si elle devrait nous laisser aller sur la page désirée.

Est-ce que tu vas en faire une PR ?

**Comment by MachiganMC** [comment]
Meilleure implémentation via la PR qui mentionne l'issue #28
