### ISSUE TITLE
Les utilisateurs connectés sont redirigés vers `/` lorsqu'ils tentent d'accéder à `/parts`.

### ISSUE THREAD

**Issue by Karitchi** [mux99/pocket-bot#41]
Il y à un bug dans le code ci-dessous redirigeant les utilisateurs connecté vers `/`.

https://github.com/mux99/pocket-bot/blob/7803e334d4f021f28ba2829397a7a2b54227f27b/src/routes/parts/%2Bpage.server.js#L1-L13

Aussi, le retour de `getUserinfo` est directement récupérable via `locals.userInfo` dans `load` grâce à ce bout de code:
https://github.com/mux99/pocket-bot/blob/7803e334d4f021f28ba2829397a7a2b54227f27b/src/hooks.server.js#L10

**Comment by MachiganMC** [comment]
Ha oui merci. J
e corrige ça, j'avais pas encore connaissance de `locals.userInfo` quand j'ai fait la la feature.
Je redirigerai du coup vers `/login`.
